export const CATEGORIES = [
  { id: 'student', label: 'Students', icon: 'GraduationCap', count: 42, color: 'emerald' },
  { id: 'farmer', label: 'Farmers', icon: 'Wheat', count: 28, color: 'amber' },
  { id: 'employee', label: 'Employees', icon: 'Briefcase', count: 19, color: 'blue' },
  { id: 'women', label: 'Women', icon: 'Heart', count: 34, color: 'rose' },
  { id: 'senior', label: 'Senior Citizens', icon: 'Users', count: 15, color: 'violet' },
  { id: 'entrepreneur', label: 'Entrepreneurs', icon: 'Rocket', count: 22, color: 'orange' },
];

export const SCHEME_TYPES = [
  { id: 'govt', label: 'Government', icon: 'Landmark' },
  { id: 'private', label: 'Private', icon: 'Building2' },
];

export const STATES = [
  'All India', 'Andhra Pradesh', 'Bihar', 'Delhi', 'Gujarat', 'Karnataka',
  'Kerala', 'Maharashtra', 'Odisha', 'Punjab', 'Rajasthan', 'Tamil Nadu',
  'Telangana', 'Uttar Pradesh', 'West Bengal'
];

export const MINISTRIES = [
  'Ministry of Education', 'Ministry of Agriculture', 'Ministry of Rural Development',
  'Ministry of Women and Child Development', 'Ministry of Skill Development',
  'Ministry of Social Justice', 'Ministry of MSME', 'Ministry of Labour'
];

// "ministry" is used for govt schemes; private schemes use "provider" instead.
export const SCHEMES = [
  {
    id: 'pm-yasasvi',
    title: 'PM YASASVI Scholarship',
    type: 'govt',
    ministry: 'Ministry of Social Justice',
    category: 'student',
    state: 'All India',
    tags: ['Scholarship', 'OBC', 'EBC'],
    benefit: '₹75,000 - ₹1,25,000 / year',
    deadline: '2026-10-31',
    description: 'Pre-matric and post-matric scholarship for OBC, EBC, and DNT students to support quality education from Class 9 to postgraduate level.',
    eligibility: {
      age: [10, 30],
      income: 250000,
      categories: ['OBC', 'EBC', 'DNT'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      'Tuition fee reimbursement up to ₹1.25 lakh per year',
      'Academic allowance of ₹3,000 per month',
      'One-time book allowance of ₹5,000',
      'Free hostel accommodation for eligible students'
    ],
    documents: ['Aadhaar Card', 'Income Certificate', 'Caste Certificate', 'Marksheet', 'Bank Passbook'],
    applyLink: 'https://yet.nta.ac.in',
    featured: true,
  },
  {
    id: 'pm-kisan',
    title: 'PM Kisan Samman Nidhi',
    type: 'govt',
    ministry: 'Ministry of Agriculture',
    category: 'farmer',
    state: 'All India',
    tags: ['Direct Benefit', 'Income Support'],
    benefit: '₹6,000 / year',
    deadline: '2026-07-15',
    description: 'Direct income support of ₹6,000 per year in three equal installments to all landholding farmer families across the country.',
    eligibility: {
      age: [18, 100],
      income: 999999,
      categories: ['any'],
      occupation: ['farmer'],
      gender: ['any'],
    },
    benefits: [
      '₹2,000 every four months directly to bank account',
      'No paperwork after registration',
      'Covers all landholding farmer families',
      'Additional state-level top-ups in some states'
    ],
    documents: ['Aadhaar Card', 'Land Records', 'Bank Passbook', 'Ration Card'],
    applyLink: 'https://pmkisan.gov.in',
    featured: true,
  },
  {
    id: 'nsp-central',
    title: 'Central Sector Scholarship',
    type: 'govt',
    ministry: 'Ministry of Education',
    category: 'student',
    state: 'All India',
    tags: ['Merit', 'Higher Education'],
    benefit: '₹10,000 - ₹20,000 / year',
    deadline: '2026-11-30',
    description: 'Merit-based scholarship for meritorious students from low-income families pursuing higher education in colleges and universities.',
    eligibility: {
      age: [17, 25],
      income: 800000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      '₹10,000 per year for first three years of graduation',
      '₹20,000 per year for post-graduation',
      'Direct bank transfer via DBT',
      'Renewable subject to academic performance'
    ],
    documents: ['Aadhaar Card', 'Income Certificate', '12th Marksheet', 'College Admission Proof', 'Bank Passbook'],
    applyLink: 'https://scholarships.gov.in',
    featured: true,
  },
  {
    id: 'mudra-yojana',
    title: 'Pradhan Mantri MUDRA Yojana',
    type: 'govt',
    ministry: 'Ministry of MSME',
    category: 'entrepreneur',
    state: 'All India',
    tags: ['Loan', 'Business', 'MSME'],
    benefit: 'Loan up to ₹10 lakh',
    deadline: '2026-07-19',
    description: 'Collateral-free loans up to ₹10 lakh for micro and small enterprises through Shishu, Kishore, and Tarun categories.',
    eligibility: {
      age: [18, 65],
      income: 999999,
      categories: ['any'],
      occupation: ['entrepreneur', 'employee'],
      gender: ['any'],
    },
    benefits: [
      'Shishu: Loans up to ₹50,000',
      'Kishore: Loans from ₹50,001 to ₹5 lakh',
      'Tarun: Loans from ₹5 lakh to ₹10 lakh',
      'No collateral required'
    ],
    documents: ['Aadhaar Card', 'PAN Card', 'Business Plan', 'Bank Statements', 'Address Proof'],
    applyLink: 'https://mudra.org.in',
    featured: false,
  },
  {
    id: 'sukanya-samriddhi',
    title: 'Sukanya Samriddhi Yojana',
    type: 'govt',
    ministry: 'Ministry of Women and Child Development',
    category: 'women',
    state: 'All India',
    tags: ['Savings', 'Girl Child'],
    benefit: '8.2% interest rate',
    deadline: '2026-09-05',
    description: 'Small savings scheme for the girl child offering attractive interest rates and tax benefits for parents.',
    eligibility: {
      age: [0, 10],
      income: 999999,
      categories: ['any'],
      occupation: ['any'],
      gender: ['female'],
    },
    benefits: [
      'Attractive 8.2% interest rate (compounded annually)',
      'Tax deduction under Section 80C',
      'Minimum deposit ₹250, maximum ₹1.5 lakh per year',
      'Maturity after 21 years'
    ],
    documents: ['Birth Certificate of Girl Child', 'Aadhaar of Parent', 'Address Proof'],
    applyLink: 'https://www.nsiindia.gov.in',
    featured: true,
  },
  {
    id: 'atal-pension',
    title: 'Atal Pension Yojana',
    type: 'govt',
    ministry: 'Ministry of Labour',
    category: 'senior',
    state: 'All India',
    tags: ['Pension', 'Retirement'],
    benefit: '₹1,000 - ₹5,000 monthly pension',
    deadline: '2026-08-25',
    description: 'Guaranteed monthly pension scheme for citizens in the unorganized sector between 18 and 40 years.',
    eligibility: {
      age: [18, 40],
      income: 999999,
      categories: ['any'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      'Guaranteed pension from ₹1,000 to ₹5,000 per month',
      'Government co-contribution for eligible subscribers',
      'Spouse and nominee benefits',
      'Low monthly contribution starting at ₹42'
    ],
    documents: ['Aadhaar Card', 'Bank Account', 'Mobile Number'],
    applyLink: 'https://npscra.nsdl.co.in',
    featured: false,
  },
  {
    id: 'skill-india',
    title: 'PMKVY - Skill India',
    type: 'govt',
    ministry: 'Ministry of Skill Development',
    category: 'employee',
    state: 'All India',
    tags: ['Training', 'Certification', 'Free'],
    benefit: 'Free training + certification',
    deadline: '2026-07-28',
    description: 'Free short-term skill training and certification to help youth become employable and earn a livelihood.',
    eligibility: {
      age: [15, 45],
      income: 999999,
      categories: ['any'],
      occupation: ['employee', 'student'],
      gender: ['any'],
    },
    benefits: [
      'Completely free skill training',
      'Industry-recognized certification',
      'Placement assistance after training',
      'Monetary reward of up to ₹8,000 on successful assessment'
    ],
    documents: ['Aadhaar Card', '10th/12th Marksheet', 'Bank Passbook'],
    applyLink: 'https://pmkvyofficial.org',
    featured: false,
  },
  {
    id: 'kisan-credit',
    title: 'Kisan Credit Card Scheme',
    type: 'govt',
    ministry: 'Ministry of Agriculture',
    category: 'farmer',
    state: 'All India',
    tags: ['Credit', 'Loan', 'Agriculture'],
    benefit: 'Credit up to ₹3 lakh @ 4%',
    deadline: '2026-09-10',
    description: 'Short-term credit for farmers to meet cultivation needs, post-harvest expenses, and allied activities at subsidized interest.',
    eligibility: {
      age: [18, 75],
      income: 999999,
      categories: ['any'],
      occupation: ['farmer'],
      gender: ['any'],
    },
    benefits: [
      'Effective interest rate as low as 4% per annum',
      'Flexible repayment aligned with harvest',
      'Coverage under PMFBY crop insurance',
      'Withdraw via ATM using RuPay card'
    ],
    documents: ['Aadhaar Card', 'Land Records', 'Bank Passbook', 'Passport Photo'],
    applyLink: 'https://www.pmkisan.gov.in',
    featured: false,
  },
  {
    id: 'ujjwala',
    title: 'PM Ujjwala Yojana 2.0',
    type: 'govt',
    ministry: 'Ministry of Rural Development',
    category: 'women',
    state: 'All India',
    tags: ['LPG', 'Free Connection'],
    benefit: 'Free LPG connection',
    deadline: '2026-10-05',
    description: 'Free LPG connection to women from below poverty line households to promote clean cooking fuel.',
    eligibility: {
      age: [18, 100],
      income: 100000,
      categories: ['BPL'],
      occupation: ['any'],
      gender: ['female'],
    },
    benefits: [
      'Free deposit-free LPG connection',
      'First refill and stove free',
      'Cash assistance for equipment',
      'Health benefits from clean cooking fuel'
    ],
    documents: ['Aadhaar Card', 'BPL Certificate', 'Ration Card', 'Bank Passbook'],
    applyLink: 'https://www.pmuy.gov.in',
    featured: false,
  },
  {
    id: 'vayoshreshtha',
    title: 'Vayoshreshtha Samman',
    type: 'govt',
    ministry: 'Ministry of Social Justice',
    category: 'senior',
    state: 'All India',
    tags: ['Award', 'Recognition'],
    benefit: 'National recognition + cash',
    deadline: '2026-09-30',
    description: 'National awards for eminent senior citizens and institutions in recognition of their services towards the cause of the elderly.',
    eligibility: {
      age: [60, 120],
      income: 999999,
      categories: ['any'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      'National recognition certificate',
      'Cash award of up to ₹1 lakh',
      'Felicitation by President of India',
      'Category-wise awards'
    ],
    documents: ['Aadhaar Card', 'Age Proof', 'Nomination Form', 'Achievement Records'],
    applyLink: 'https://socialjustice.gov.in',
    featured: false,
  },
  {
    id: 'startup-india',
    title: 'Startup India Seed Fund',
    type: 'govt',
    ministry: 'Ministry of MSME',
    category: 'entrepreneur',
    state: 'All India',
    tags: ['Startup', 'Seed Funding'],
    benefit: 'Up to ₹50 lakh funding',
    deadline: '2026-11-15',
    description: 'Financial assistance to startups for proof of concept, prototype development, product trials, and market entry.',
    eligibility: {
      age: [18, 65],
      income: 999999,
      categories: ['any'],
      occupation: ['entrepreneur'],
      gender: ['any'],
    },
    benefits: [
      'Grants up to ₹20 lakh for proof of concept',
      'Convertible debentures up to ₹50 lakh',
      'Mentorship and incubation support',
      'Access to Startup India network'
    ],
    documents: ['DPIIT Recognition', 'PAN Card', 'Incorporation Certificate', 'Pitch Deck'],
    applyLink: 'https://seedfund.startupindia.gov.in',
    featured: false,
  },

  // ---------- Private-sector schemes ----------
  {
    id: 'tata-pankh',
    title: 'Tata Capital Pankh Scholarship',
    type: 'private',
    provider: 'Tata Capital Limited',
    category: 'student',
    state: 'All India',
    tags: ['Scholarship', 'CSR', 'Girl Child'],
    benefit: 'Up to ₹1,00,000 / year',
    deadline: '2026-08-31',
    description: 'CSR-funded scholarship supporting meritorious students from economically weaker sections, with a focus on girl students, for undergraduate studies.',
    eligibility: {
      age: [17, 25],
      income: 400000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      'Tuition support up to ₹1 lakh per year',
      'Mentorship from Tata Capital employees',
      'Priority for first-generation learners',
      'Renewable each academic year on performance'
    ],
    documents: ['Aadhaar Card', 'Income Certificate', 'Marksheet', 'Admission Proof', 'Bank Passbook'],
    applyLink: 'https://www.tatacapital.com/pankh-scholarship.html',
    featured: false,
  },
  {
    id: 'reliance-foundation-scholarship',
    title: 'Reliance Foundation Undergraduate Scholarship',
    type: 'private',
    provider: 'Reliance Foundation',
    category: 'student',
    state: 'All India',
    tags: ['Scholarship', 'Merit'],
    benefit: '₹50,000 one-time',
    deadline: '2026-09-15',
    description: 'One-time merit-cum-means scholarship for students entering the first year of undergraduate study across disciplines.',
    eligibility: {
      age: [17, 22],
      income: 1500000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      'One-time grant of ₹50,000',
      'Networking access to Reliance Foundation alumni community',
      'Certificate of recognition',
      'Priority consideration for internship programs'
    ],
    documents: ['Aadhaar Card', 'Income Proof', '12th Marksheet', 'College Admission Letter'],
    applyLink: 'https://www.reliancefoundation.org/scholarships',
    featured: false,
  },
  {
    id: 'hdfc-parivartan-krishi',
    title: 'HDFC Bank Parivartan Krishi Udaan',
    type: 'private',
    provider: 'HDFC Bank CSR',
    category: 'farmer',
    state: 'All India',
    tags: ['Agri-Training', 'CSR', 'Livelihood'],
    benefit: 'Free agri-inputs + training',
    deadline: '2026-08-20',
    description: 'CSR initiative providing small and marginal farmers with training on modern agricultural practices, quality seeds, and market linkages.',
    eligibility: {
      age: [18, 70],
      income: 999999,
      categories: ['any'],
      occupation: ['farmer'],
      gender: ['any'],
    },
    benefits: [
      'Free training on modern farming techniques',
      'Subsidized access to quality seeds and inputs',
      'Direct market linkage support',
      'Farmer producer organization formation assistance'
    ],
    documents: ['Aadhaar Card', 'Land Records', 'Bank Passbook'],
    applyLink: 'https://www.hdfcbank.com/personal/about-us/csr/parivartan',
    featured: false,
  },
  {
    id: 'infosys-foundation-women',
    title: 'Infosys Foundation Women Entrepreneur Grant',
    type: 'private',
    provider: 'Infosys Foundation',
    category: 'women',
    state: 'All India',
    tags: ['Grant', 'CSR', 'Business'],
    benefit: 'Grant up to ₹2 lakh',
    deadline: '2026-12-15',
    description: 'Seed grants and mentorship for women-led micro and small enterprises in semi-urban and rural areas.',
    eligibility: {
      age: [21, 55],
      income: 600000,
      categories: ['any'],
      occupation: ['entrepreneur'],
      gender: ['female'],
    },
    benefits: [
      'Seed grant of up to ₹2 lakh',
      'Business mentorship for 12 months',
      'Access to Infosys Foundation vendor network',
      'Digital literacy and accounting training'
    ],
    documents: ['Aadhaar Card', 'Business Registration', 'Bank Statements', 'Income Proof'],
    applyLink: 'https://www.infosys.org/infosys-foundation',
    featured: false,
  },
  {
    id: 'lic-jeevan-senior',
    title: 'LIC Saral Pension for Senior Citizens',
    type: 'private',
    provider: 'Life Insurance Corporation of India',
    category: 'senior',
    state: 'All India',
    tags: ['Pension', 'Annuity', 'Insurance'],
    benefit: 'Guaranteed lifelong annuity',
    deadline: '2026-12-31',
    description: 'Single-premium immediate annuity plan offering guaranteed lifelong pension income for senior citizens.',
    eligibility: {
      age: [40, 80],
      income: 999999,
      categories: ['any'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      'Guaranteed pension for life',
      'Choice of annuity payout options',
      'Return of purchase price to nominee on death',
      'Loan facility available after 6 months'
    ],
    documents: ['Aadhaar Card', 'Age Proof', 'Bank Passbook', 'PAN Card'],
    applyLink: 'https://licindia.in/web/guest/saral-pension',
    featured: false,
  },
  {
    id: 'nasscom-futureskills',
    title: 'NASSCOM FutureSkills Prime Upskilling',
    type: 'private',
    provider: 'NASSCOM (Industry Consortium)',
    category: 'employee',
    state: 'All India',
    tags: ['Upskilling', 'Tech', 'Certification'],
    benefit: 'Subsidized tech certifications',
    deadline: '2026-10-30',
    description: 'Industry-backed upskilling platform offering courses and certifications in emerging technologies at subsidized rates for IT professionals.',
    eligibility: {
      age: [18, 50],
      income: 999999,
      categories: ['any'],
      occupation: ['employee'],
      gender: ['any'],
    },
    benefits: [
      'Subsidized courses in AI, cloud, and cybersecurity',
      'Industry-recognized certification on completion',
      'Access to potential employer hiring pool',
      'Self-paced online learning modules'
    ],
    documents: ['Aadhaar Card', 'Employment Proof or Resume'],
    applyLink: 'https://futureskillsprime.in',
    featured: false,
  },
  {
    id: 'ab-pmjay',
    title: 'Ayushman Bharat (PM-JAY)',
    ministry: 'Ministry of Health and Family Welfare',
    category: 'employee', // Accessible to unorganized workers/families
    state: 'All India',
    tags: ['Healthcare', 'Insurance', 'Free Medical'],
    benefit: '₹5 Lakh health cover / family / year',
    deadline: '2026-12-30',
    description: 'The world’s largest health insurance scheme providing free secondary and tertiary care hospitalization to vulnerable families.',
    eligibility: {
      age: [0, 100],
      income: 120000,
      categories: ['BPL', 'SC', 'ST'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      'Cashless and paperless access to healthcare services',
      'Covers up to 3 days of pre-hospitalization and 15 days post-hospitalization',
      'No restriction on family size, age, or gender',
      'All pre-existing conditions are covered from day one'
    ],
    documents: ['Aadhaar Card', 'Ration Card (PM-JAY Letter)', 'Income Certificate'],
    applyLink: 'https://pmjay.gov.in',
    featured: true,
  },
  {
    id: 'pmsvanidhi',
    title: 'PM SVANidhi Scheme',
    ministry: 'Ministry of Housing and Urban Affairs',
    category: 'entrepreneur',
    state: 'All India',
    tags: ['Loan', 'Street Vendor', 'Micro-credit'],
    benefit: 'Working capital loan up to ₹50,000',
    deadline: '2026-11-12',
    description: 'A special micro-credit facility scheme for providing affordable working capital loans to street vendors to resume their livelihoods.',
    eligibility: {
      age: [18, 65],
      income: 999999,
      categories: ['any'],
      occupation: ['entrepreneur'],
      gender: ['any'],
    },
    benefits: [
      'Initial working capital loan of up to ₹10,000',
      '7% interest subsidy on timely/early repayment',
      'Cashback incentives up to ₹1,200 per year on digital transactions',
      'Eligibility for enhanced next-cycle loan of ₹20,000 and ₹50,000'
    ],
    documents: ['Aadhaar Card', 'Voter ID Card', 'Certificate of Vending (COV)'],
    applyLink: 'https://pmsvanidhi.mohua.gov.in',
    featured: false,
  },
  {
    id: 'pmsby',
    title: 'PM Suraksha Bima Yojana',
    ministry: 'Ministry of Finance',
    category: 'employee',
    state: 'All India',
    tags: ['Insurance', 'Accident Cover'],
    benefit: '₹2 Lakh accident insurance',
    deadline: '2026-08-18',
    description: 'An affordable, government-backed accident insurance scheme for citizens with auto-debit facility from bank accounts.',
    eligibility: {
      age: [18, 70],
      income: 999999,
      categories: ['any'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      '₹2 Lakh coverage for accidental death or total permanent disability',
      '₹1 Lakh coverage for partial permanent disability',
      'Extremely low premium of just ₹20 per annum',
      'Seamless auto-debit renewal process'
    ],
    documents: ['Aadhaar Card', 'Bank Passbook', 'Nominee Details'],
    applyLink: 'https://jansuraksha.gov.in',
    featured: false,
  },
  {
    id: 'pmmvy',
    title: 'Pradhan Mantri Matru Vandana Yojana',
    ministry: 'Ministry of Women and Child Development',
    category: 'women',
    state: 'All India',
    tags: ['Maternity Benefit', 'Direct Benefit'],
    benefit: '₹5,000 cash incentive',
    deadline: '2026-09-22',
    description: 'A maternity benefit program providing direct cash incentives to pregnant and lactating mothers for the first living child.',
    eligibility: {
      age: [19, 45],
      income: 999999,
      categories: ['any'],
      occupation: ['any'],
      gender: ['female'],
    },
    benefits: [
      'Cash incentives paid directly to bank accounts via DBT',
      'Promotes safe delivery and optimal infant feeding practices',
      'Compensation for wage loss during childbirth',
      'Linked to routine immunization cycles'
    ],
    documents: ['Aadhaar Card', 'MCP Card (Mother and Child Protection)', 'Bank Passbook'],
    applyLink: 'https://pmmvy.wcd.gov.in',
    featured: false,
  },
  {
    id: 'pm-shram-yogi',
    title: 'PM Shram Yogi Maan-dhan',
    ministry: 'Ministry of Labour',
    category: 'senior',
    state: 'All India',
    tags: ['Pension', 'Unorganized Sector'],
    benefit: '₹3,000 guaranteed monthly pension',
    deadline: '2026-08-28',
    description: 'A voluntary and contributory pension scheme for unorganized workers like street vendors, rickshaw pullers, and domestic helpers.',
    eligibility: {
      age: [18, 40],
      income: 180000,
      categories: ['any'],
      occupation: ['employee'],
      gender: ['any'],
    },
    benefits: [
      'Assured monthly pension of ₹3,000 after reaching age 60',
      'Matching 50:50 contribution by the Central Government',
      'Family pension of 50% to spouse in case of death',
      'Easy exit plans with accumulated interest auto-credited'
    ],
    documents: ['Aadhaar Card', 'Savings Bank Account Account / Jan Dhan Account'],
    applyLink: 'https://maandhan.in',
    featured: false,
  },
  {
    id: 'reliance-dhubhai',
    title: 'Reliance Foundation Scholarship',
    ministry: 'Private: Reliance Foundation',
    category: 'student',
    state: 'All India',
    tags: ['Private', 'Scholarship', 'Undergraduate'],
    benefit: 'Up to ₹2,00000 - ₹6,00000 / degree',
    deadline: '2026-10-15',
    description: 'Private merit-cum-means scholarship supporting meritorious Indian students pursuing full-time undergraduate or postgraduate degrees.',
    eligibility: {
      age: [17, 25],
      income: 1500000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      'Financial support up to ₹2 Lakh for UG and ₹6 Lakh for PG',
      'Access to an active global alumni network',
      'Exclusive leadership and professional development workshops',
      'Internship opportunities within partner ecosystems'
    ],
    documents: ['Aadhaar Card', '12th/Graduation Marksheet', 'Income Certificate', 'Current College Admission Proof'],
    applyLink: 'https://www.scholarships.reliancefoundation.org',
    featured: true,
  },
  {
    id: 'hdfc-badhte-kadam',
    title: 'HDFC Bank Parivartan Scholarship',
    ministry: 'Private: HDFC Bank',
    category: 'student',
    state: 'All India',
    tags: ['Private', 'Scholarship', 'School & College'],
    benefit: '₹15,000 - ₹75,000 / year',
    deadline: '2026-09-30',
    description: 'A CSR initiative by HDFC Bank aiming to assist smart students facing financial hardships or family crises to continue their education.',
    eligibility: {
      age: [6, 26],
      income: 600000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      'School students (Class 1-12) receive up to ₹15,000',
      'Diploma and undergraduate students receive up to ₹30,000',
      'Professional courses (B.Tech/MBBS/MBA) receive up to ₹75,000',
      'Special preference given to students facing sudden parental job loss or health crises'
    ],
    documents: ['Previous Academic Marksheet', 'Family Income Certificate', 'Identity Proof', 'Crisis Proof (if applicable)'],
    applyLink: 'https://www.buddy4study.com/page/hdfc-bank-parivartans-ecss-scholarship',
    featured: false,
  },
  {
    id: 'tata-samarth',
    title: 'Tata Samarth Scheme',
    ministry: 'Private: Tata Motors',
    category: 'farmer',
    state: 'All India',
    tags: ['Private', 'Welfare', 'Commercial Driver'],
    benefit: 'Scholarship + ₹10 Lakh Life Cover',
    deadline: '2026-07-05',
    description: 'A dedicated welfare initiative designed to provide financial, health, and academic security to commercial vehicle drivers and owner-drivers.',
    eligibility: {
      age: [18, 60],
      income: 500000,
      categories: ['any'],
      occupation: ['farmer', 'employee'],
      gender: ['any'],
    },
    benefits: [
      '₹10 Lakh accidental death & permanent disability insurance cover',
      'Health insurance up to ₹1 Lakh for family treatments',
      'Higher education scholarships for drivers’ children',
      'Financial support for daughters’ weddings'
    ],
    documents: ['Commercial Driving License', 'Aadhaar Card', 'Vehicle Ownership Papers / Employment Proof'],
    applyLink: 'https://www.tatamotors.com',
    featured: false,
  },
  {
    id: 'infosys-foundation-aarohan',
    title: 'Infosys Aarohan Social Innovation Awards',
    ministry: 'Private: Infosys Foundation',
    category: 'entrepreneur',
    state: 'All India',
    tags: ['Private', 'Innovation', 'Cash Prize'],
    benefit: 'Cash prize up to ₹20 Lakh',
    deadline: '2026-12-15',
    description: 'Awards created to recognize, celebrate, and support grassroot innovations that offer realistic solutions for social welfare.',
    eligibility: {
      age: [18, 75],
      income: 999999,
      categories: ['any'],
      occupation: ['entrepreneur'],
      gender: ['any'],
    },
    benefits: [
      'Top innovators receive mega cash rewards up to ₹20 Lakh',
      'Opportunity for product incubation and mentorship by industry leaders',
      'Travel and exhibition grants to display work globally',
      'IP/Patent filing advisory support'
    ],
    documents: ['Project Prototype Report', 'PAN Card', 'Video Demonstration / Pitch Deck'],
    applyLink: 'https://www.infosys.com/infosys-foundation/aarohan-awards.html',
    featured: true,
  },
  {
    id: 'loreal-women-science',
    title: 'L’Oréal India For Young Women in Science',
    ministry: 'Private: L’Oréal India',
    category: 'women',
    state: 'All India',
    tags: ['Private', 'Scholarship', 'STEM'],
    benefit: '₹2,50,000 / student',
    deadline: '2026-10-15',
    description: 'Financial aid provided to young women who have passed Class 12 and wish to pursue a graduation degree in any scientific field (STEM).',
    eligibility: {
      age: [16, 19],
      income: 600000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['female'],
    },
    benefits: [
      'Total scholarship of ₹2.5 Lakh distributed over college years',
      'Covers tuition fees, books, and educational materials',
      'One-on-one mentorship sessions with female scientists',
      'Invitations to research symposia and technical networking meetups'
    ],
    documents: ['Class 10 and 12 Marksheets (Minimum 85% in PCM/PCB)', 'Income Proof', 'Aadhaar Card', 'College Admission Letter'],
    applyLink: 'https://www.foryoungwomeninscience.co.in',
    featured: false,
  },
  {
    id: 'pm-poshan',
    title: 'PM Poshan Shakti Nirman',
    type: 'govt',
    ministry: 'Ministry of Education',
    category: 'student',
    state: 'All India',
    tags: ['Nutrition', 'School Meal', 'Primary Education'],
    benefit: 'Free nutritious hot-cooked meals',
    deadline: 'Ongoing',
    description: 'Providing free nutritious cooked meals to school children in government and government-aided schools to improve nutritional status and enrollment.',
    eligibility: {
      age: [5, 14],
      income: 150000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      'Free daily hot-cooked meal at school',
      'Covers calories and protein requirements as per norms',
      'Covers children from Class 1 to Class 8',
      'Improves class attendance and concentration'
    ],
    documents: ['School ID Card', 'Aadhaar Card', 'Parental Income Certificate'],
    applyLink: 'https://education.gov.in',
    featured: false,
  },
  {
    id: 'nmmss-scholarship',
    title: 'National Means-cum-Merit Scholarship Scheme',
    type: 'govt',
    ministry: 'Ministry of Education',
    category: 'student',
    state: 'All India',
    tags: ['Scholarship', 'Merit', 'Secondary School'],
    benefit: '₹12,000 / year',
    deadline: '2026-10-31',
    description: 'Scholarship to award-winning and meritorious students of economically weaker sections to arrest their drop-out at class VIII and encourage them to continue study at secondary stage.',
    eligibility: {
      age: [10, 16],
      income: 350000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      '₹12,000 yearly scholarship deposited directly',
      'Continuous support from Class 9 to Class 12',
      'Assures educational continuity for bright students',
      'Exempt from other state level restriction matchings'
    ],
    documents: ['Class 7 Marksheet', 'Aadhaar Card', 'Parental Income Certificate', 'Caste Certificate'],
    applyLink: 'https://scholarships.gov.in',
    featured: false,
  },
  {
    id: 'pm-pranam',
    title: 'PM-PRANAM Scheme',
    type: 'govt',
    ministry: 'Ministry of Agriculture',
    category: 'farmer',
    state: 'All India',
    tags: ['Subsidy', 'Organic Farming', 'Fertilizer'],
    benefit: 'Organic fertilizer subsidy up to ₹15,000',
    deadline: 'Ongoing',
    description: 'Program for Restoration, Awareness, Nourishment and Amelioration of Mother Earth to promote balanced use of chemical fertilizers along with alternative nutrients.',
    eligibility: {
      age: [18, 75],
      income: 999999,
      categories: ['any'],
      occupation: ['farmer'],
      gender: ['any'],
    },
    benefits: [
      '₹15,000 subsidy/incentive for installing organic fertilizer plants',
      'Free training on organic and bio-fertilizer compost creation',
      'Soil health card testing support at no cost',
      'Grants given to local cooperative groups for fertilizer setup'
    ],
    documents: ['Land Holding Records', 'Aadhaar Card', 'Bank Passbook', 'Soil Health Card (if available)'],
    applyLink: 'https://agricoop.nic.in',
    featured: false,
  },
  {
    id: 'mahila-coir',
    title: 'Mahila Coir Yojana',
    type: 'govt',
    ministry: 'Ministry of MSME',
    category: 'women',
    state: 'All India',
    tags: ['Self-Employment', 'Coir Industry', 'Artisan'],
    benefit: '75% machinery subsidy + free training',
    deadline: 'Ongoing',
    description: 'Women self-employment program providing training and subsidized spinning machinery for the coir processing and product development industry.',
    eligibility: {
      age: [18, 60],
      income: 250000,
      categories: ['any'],
      occupation: ['entrepreneur'],
      gender: ['female'],
    },
    benefits: [
      '75% subsidy on cost of motorized coir spinning equipment',
      '2-month free training course with ₹3,000 monthly stipend',
      'Linkage to marketing outlets and self-help groups',
      'Business startup assistance under MSME guidelines'
    ],
    documents: ['Aadhaar Card', 'Address Proof', 'Income Certificate', 'Coir Board Training Certificate'],
    applyLink: 'https://coirboard.gov.in',
    featured: false,
  },
  {
    id: 'pm-janaushadhi',
    title: 'PM Janaushadhi Sugam Scheme',
    type: 'govt',
    ministry: 'Ministry of Chemical and Fertilizer',
    category: 'employee',
    state: 'All India',
    tags: ['Medicines', 'Healthcare', 'Generic Drugs'],
    benefit: '50% - 90% savings on generic medicines',
    deadline: 'Ongoing',
    description: 'Making quality generic medicines available to all at affordable prices through designated Pradhan Mantri Bhartiya Janaushadhi Kendras.',
    eligibility: {
      age: [0, 120],
      income: 999999,
      categories: ['any'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      '50% to 90% cheaper price than branded counterparts',
      'Generic medicines matching international therapeutic standards',
      'Nationwide availability across 10,000+ kendras',
      'Includes critical wellness products and surgical consumables'
    ],
    documents: ['Aadhaar Card', 'Doctor\'s Prescription'],
    applyLink: 'https://janaushadhi.gov.in',
    featured: false,
  },
  {
    id: 'standup-india',
    title: 'Stand-Up India Scheme',
    type: 'govt',
    ministry: 'Ministry of Finance',
    category: 'entrepreneur',
    state: 'All India',
    tags: ['Business Loan', 'SC ST', 'Women Entrepreneur'],
    benefit: 'Loan between ₹10 Lakh and ₹1 Crore',
    deadline: 'Ongoing',
    description: 'Promotes entrepreneurship at the grassroots level, focusing on economic empowerment and job creation of Scheduled Caste, Scheduled Tribe, and women entrepreneurs.',
    eligibility: {
      age: [18, 70],
      income: 999999,
      categories: ['SC', 'ST'],
      occupation: ['entrepreneur'],
      gender: ['any'],
    },
    benefits: [
      'Collateral-free loan from ₹10 lakh up to ₹1 crore',
      'Covers up to 75% of greenfield project cost',
      'Flexible repayment period of 7 years with 18 months moratorium',
      'Comprehensive pre-loan tutoring and networking support'
    ],
    documents: ['Detailed Project/Business Report', 'Aadhaar Card', 'PAN Card', 'Caste Certificate (if SC/ST)', 'Bank Statement (6 months)', 'Partnership/Deed Papers'],
    applyLink: 'https://www.standupmitra.in',
    featured: false,
  },
  {
    id: 'pmay-gramin',
    title: 'PM Awas Yojana - Gramin',
    type: 'govt',
    ministry: 'Ministry of Rural Development',
    category: 'farmer',
    state: 'All India',
    tags: ['Housing', 'Rural Welfare', 'Financial Support'],
    benefit: 'Housing assistance up to ₹1.2 Lakh',
    deadline: 'Ongoing',
    description: 'Provide financial assistance to rural BPL families for construction of pucca houses with clean sanitation and cooking facilities.',
    eligibility: {
      age: [18, 120],
      income: 200000,
      categories: ['any'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      '₹1,20,000 assistance in plains and ₹1,30,000 in hilly/difficult areas',
      'Convergence with Swachh Bharat for toilet construction unit',
      '90-95 mandays of unskilled labour wage under MNREGA',
      'Safe and permanent housing with basic amenities'
    ],
    documents: ['Aadhaar Card', 'SECC/BPL Registration ID', 'Ration Card', 'Bank Account details', 'Self-Declaration Certificate'],
    applyLink: 'https://pmayg.nic.in',
    featured: false,
  },
  {
    id: 'ntpc-disabled-scholarship',
    title: 'NTPC CSR Disability Scholarship',
    type: 'private',
    provider: 'NTPC Limited CSR',
    category: 'student',
    state: 'All India',
    tags: ['Scholarship', 'Private', 'Disability Support'],
    benefit: '₹15,000 / year',
    deadline: '2026-07-31',
    description: 'CSR scholarship program to assist talented differently-abled students from poor families pursuing commercial or technical education.',
    eligibility: {
      age: [12, 25],
      income: 300000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      '₹15,000 annual scholarship for diploma/undergraduate education',
      'Mentorship and industrial site visits for scholars',
      'Full reimbursement of books and study gear up to ₹3,000',
      'Career counseling and interview readiness training'
    ],
    documents: ['UDID Card / Disability Certificate', 'Class 10/12 Marksheet', 'Parental Income Certificate', 'Aadhaar Card', 'Admission Fee Invoice'],
    applyLink: 'https://www.ntpc.co.in',
    featured: false,
  },
  {
    id: 'igndps-pension',
    title: 'IGNDPS Disability Pension',
    type: 'govt',
    ministry: 'Ministry of Rural Development',
    category: 'senior',
    state: 'All India',
    tags: ['Pension', 'Severe Disability', 'Social Care'],
    benefit: '₹600 / month pension',
    deadline: 'Ongoing',
    description: 'Providing monthly security pension to differently-abled persons with severe or multiple disabilities belonging to BPL households.',
    eligibility: {
      age: [18, 79],
      income: 150000,
      categories: ['any'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      '₹600 monthly pension directly to bank account via DBT',
      'Eligible to move to Indira Gandhi Old Age Pension Scheme at age 80',
      'Assures baseline financial support for severely disabled citizens',
      'State government additionals depending on regional guidelines'
    ],
    documents: ['Disability Certificate (80% and above disability)', 'Aadhaar Card', 'Ration Card / BPL card', 'Bank Passbook'],
    applyLink: 'https://nsap.nic.in',
    featured: false,
  },
  {
    id: 'fishermen-welfare',
    title: 'National Fishermen Ban Period Support',
    type: 'govt',
    ministry: 'Ministry of Fisheries',
    category: 'employee',
    state: 'All India',
    tags: ['Livelihood Relief', 'Fishermen Welfare', 'Financial Support'],
    benefit: '₹4,500 relief payout',
    deadline: 'Ongoing',
    description: 'Financial assistance and relief to marine fishermen during the official seasonal conservation bans when fishing activities are legally suspended.',
    eligibility: {
      age: [18, 65],
      income: 200000,
      categories: ['any'],
      occupation: ['employee'],
      gender: ['any'],
    },
    benefits: [
      '₹4,500 livelihood relief deposited in bank during ban period',
      'Subsidized life jacket kits and safety equipment kits',
      'Priority access to interest-free fisheries capital loans',
      'Skill enhancement training in post-harvest processing'
    ],
    documents: ['Fisherman Registration Certificate', 'Aadhaar Card', 'Active Co-operative Membership card', 'Bank Passbook'],
    applyLink: 'https://dof.gov.in',
    featured: false,
  },
  {
    id: 'pmjjby',
    title: 'PM Jeevan Jyoti Bima Yojana',
    type: 'govt',
    ministry: 'Ministry of Finance',
    category: 'employee',
    state: 'All India',
    tags: ['Life Insurance', 'Term Coverage', 'Social Security'],
    benefit: '₹2 Lakh life cover',
    deadline: 'Ongoing',
    description: 'A one-year term life insurance scheme offerable through bank accounts, providing financial security to the family in case of death of the member.',
    eligibility: {
      age: [18, 50],
      income: 999999,
      categories: ['any'],
      occupation: ['any'],
      gender: ['any'],
    },
    benefits: [
      '₹2,00,000 risk coverage on death of the insured for any reason',
      'Extremely economical premium of ₹436 per annum',
      'Auto-debit from savings bank account makes renewal easy',
      'Tax exemption benefits on premium under section 80C'
    ],
    documents: ['Aadhaar Card', 'Savings Bank Account details', 'Nominee details', 'Consent declaration form'],
    applyLink: 'https://www.jansuraksha.gov.in',
    featured: false,
  },
  {
    id: 'gyanodaya-laptop',
    title: 'Gyanodaya Free Laptop Scheme',
    type: 'govt',
    ministry: 'Ministry of Education',
    category: 'women',
    state: 'All India',
    tags: ['Student Aid', 'Women Education', 'Laptop Gadget'],
    benefit: 'Free high-perf learning laptop',
    deadline: '2026-09-30',
    description: 'An initiative to provide free high-configuration learning laptops to meritorious collegiate girls from families with restricted annual income.',
    eligibility: {
      age: [15, 22],
      income: 250000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['female'],
    },
    benefits: [
      'Free Intel Core i3 or equivalent laptop with Windows 11 pre-installed',
      '1-year free student license for Microsoft Office tools',
      'Promotes digital literacy and self-paced technical learning',
      'Aids remote class learning and competitive exam preparation'
    ],
    documents: ['Class 10 and 12 Marksheets', 'Permanent Residence Certificate', 'Parental Income Certificate', 'Aadhaar Card', 'College Admission Proof'],
    applyLink: 'https://education.gov.in',
    featured: false,
  },
  {
    id: 'azim-premji-fellowship',
    title: 'Azim Premji Fellowship',
    type: 'private',
    provider: 'Azim Premji Foundation',
    category: 'student',
    state: 'All India',
    tags: ['Fellowship', 'Education Research', 'Social Work'],
    benefit: '₹35,000 / month stipend',
    deadline: '2026-08-31',
    description: 'Exclusive 2-year fellowship program designed for young professionals and graduates to work in critical areas of public education and rural development.',
    eligibility: {
      age: [21, 35],
      income: 999999,
      categories: ['any'],
      occupation: ['student', 'employee'],
      gender: ['any'],
    },
    benefits: [
      'Monthly stipend of ₹35,050 throughout the 2-year term',
      'Extensive field training and social infrastructure exposure',
      'High chance of permanent job absorption within the foundation',
      'Post-program fellowship startup funding grants up to ₹2 lakh'
    ],
    documents: ['Graduation Degree Certificate', 'Curriculum Vitae (CV)', 'Statement of Purpose (SOP)', 'Aadhaar Card', 'Two Reference Letters'],
    applyLink: 'https://azimpremjifoundation.org',
    featured: false,
  },
  {
    id: 'jindal-scholarship',
    title: 'Sitaram Jindal Foundation Scholarship',
    type: 'private',
    provider: 'Sitaram Jindal Foundation',
    category: 'student',
    state: 'All India',
    tags: ['Scholarship', 'Private', 'EWS Aid'],
    benefit: '₹12,000 - ₹24,000 / year',
    deadline: '2026-09-15',
    description: 'Scholarship for economically backward class students pursuing technical, professional, or general undergraduate and postgraduate degrees.',
    eligibility: {
      age: [15, 25],
      income: 250000,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      'Yearly scholarship ranging from ₹12,000 to ₹24,000',
      'Covers tuition fee, college hostels, and book expenses',
      'Special sub-grants for differently-abled and orphan students',
      'Continuous funding support upon maintaining good academic standing'
    ],
    documents: ['Academic Marksheets', 'Family Income Certificate', 'College Fee Receipt & ID Card', 'Aadhaar Card', 'Recommendation letter from Principal'],
    applyLink: 'https://sitaramjindalfoundation.org',
    featured: false,
  },
  {
    id: 'lt-build-india',
    title: 'L&T Build India Scholarship',
    type: 'private',
    provider: 'Larsen & Tourbo Limited Corporate',
    category: 'student',
    state: 'All India',
    tags: ['Engineering', 'MTech Sponsorship', 'Private'],
    benefit: 'Free M.Tech at IIT/NIT + stipend',
    deadline: '2026-08-15',
    description: 'Industry-sponsored higher education opportunity for smart engineering graduates, funding their M.Tech in construction technology at premier institutes with a job offer.',
    eligibility: {
      age: [20, 26],
      income: 999999,
      categories: ['any'],
      occupation: ['student'],
      gender: ['any'],
    },
    benefits: [
      'Full M.Tech tuition sponsorship at IIT Madras, Delhi or NIT Suratkal',
      'Monthly stipend of ₹13,400 during course duration',
      'Premium industry mentorship by L&T expert engineers',
      'Guaranteed job placement at L&T on successful completion'
    ],
    documents: ['B.Tech/BE Degree Marksheets (60%+ marks)', 'Aadhaar Card', 'Resume', 'College Admission Offer letter', 'Passport photograph'],
    applyLink: 'https://www.lntecc.com',
    featured: false,
  }
];

// Expand to 50 items programmatically
const statesPool = ["Maharashtra", "Tamil Nadu", "Delhi", "Telangana", "West Bengal", "Uttar Pradesh", "Karnataka", "Gujarat", "Punjab", "Bihar"];
const extraTemplates = [
  {
    name: "Higher Education Scholarship",
    ministry: "State Department of Education",
    category: "student",
    description: "Financial assistance for pursuing post-matric studies in general and technical streams.",
    age: [16, 25],
    income: 250000,
    categories: ["any"],
    occupation: ["student"],
    gender: ["any"],
    benefit: "₹18,000 yearly scholarship",
    documents: ["Marksheet", "Income certificate", "Aadhaar Card"],
    applyLink: "https://education.gov.in"
  },
  {
    name: "Youth Entrepreneurship Loan Facilitation",
    ministry: "Private: Industrial Development Union",
    category: "entrepreneur",
    description: "Collateral free working capital and equipment loan for young local business starters.",
    age: [21, 45],
    income: 600000,
    categories: ["any"],
    occupation: ["entrepreneur"],
    gender: ["any"],
    benefit: "Subsidized loan up to ₹2,00,050",
    documents: ["Project Report", "Aadhaar Card", "PAN Card", "ITR"],
    applyLink: "https://startup.helper.org"
  },
  {
    name: "Krishi Samridhi Subsidy",
    ministry: "Ministry of Agriculture",
    category: "farmer",
    description: "Subsidy for purchasing modern agricultural machinery and organic seeds.",
    age: [18, 70],
    income: 300000,
    categories: ["any"],
    occupation: ["farmer"],
    gender: ["any"],
    benefit: "₹25,000 seed subsidy",
    documents: ["Land ownership proof", "Aadhaar Card", "Bank copy"],
    applyLink: "https://agricoop.nic.in"
  },
  {
    name: "Vulnerable Widow Self-Reliance Grant",
    ministry: "Ministry of Social Justice Welfare",
    category: "women",
    description: "Financial grant to help widows establish self-employment ventures.",
    age: [35, 65],
    income: 180000,
    categories: ["any"],
    occupation: ["any"],
    gender: ["female"],
    benefit: "₹50,000 one-time setup grant",
    documents: ["Death certificate", "Identity proof", "BPL Certificate"],
    applyLink: "https://socialwelfare.nic.in"
  },
  {
    name: "Senior Citizens Healthcare Support Plus",
    ministry: "Private: Red Cross Alliance",
    category: "senior",
    description: "Subsidized health insurance and diagnostics cover for elderly people.",
    age: [60, 95],
    income: 400000,
    categories: ["any"],
    occupation: ["any"],
    gender: ["any"],
    benefit: "Diagnostics offset up to ₹50,000/year",
    documents: ["Age proof", "Aadhaar Card", "Health declarations"],
    applyLink: "https://redcross.org"
  },
  {
    name: "Unorganized Labours Medical Aid",
    ministry: "Ministry of Labour",
    category: "employee",
    description: "Emergency medical expense coverage for daily wage workers and unorganized laborers.",
    age: [18, 55],
    income: 150000,
    categories: ["any"],
    occupation: ["employee"],
    gender: ["any"],
    benefit: "Medical coverage up to ₹30,000/year",
    documents: ["Labour registration ID", "Medical bills", "Aadhaar Card"],
    applyLink: "https://labour.gov.in"
  }
];

// Generate 23 items to reach 50 mock schemes
for (let i = 0; i < 23; i++) {
  const temp = extraTemplates[i % extraTemplates.length];
  const state = statesPool[i % statesPool.length];

  const deadlineDays = (i % 7) * 5 + 4; // e.g. 4, 9, 14, 19, 24, 29, 34 days
  const today = new Date();
  today.setDate(today.getDate() + (i % 2 === 0 ? deadlineDays : -deadlineDays + 10));

  SCHEMES.push({
    id: `extra-scheme-${i}`,
    title: `${state} ${temp.name} (Phase ${Math.floor(i / 10) + 1})`,
    ministry: temp.ministry,
    category: temp.category,
    state: state,
    tags: [temp.category, 'State Plan'],
    benefit: temp.benefit,
    deadline: today.toISOString().split('T')[0],
    description: `${temp.description} Dedicated program for eligible candidates in ${state}.`,
    eligibility: {
      age: temp.age,
      income: temp.income,
      categories: temp.categories,
      occupation: temp.occupation,
      gender: temp.gender
    },
    benefits: [temp.benefit, "Mentorship and local guidance support"],
    documents: temp.documents,
    applyLink: temp.applyLink,
    featured: false
  });
}

export const STATS = [
  { label: 'Active Schemes', value: '160+', icon: 'Layers' },
  { label: 'Beneficiaries', value: '2.4Cr', icon: 'Users' },
  { label: 'States Covered', value: '28+', icon: 'MapPin' },
  { label: 'Categories', value: '6', icon: 'LayoutGrid' },
];

export const TESTIMONIALS = [
  {
    name: 'Priya Sharma',
    role: 'Postgraduate Student, Delhi',
    text: 'Found three scholarships in five minutes. The eligibility checker saved me weeks of research.',
    initials: 'PS',
  },
  {
    name: 'Ramesh Yadav',
    role: 'Farmer, Uttar Pradesh',
    text: 'Applied for PM Kisan and got the benefits within a month. The instructions were very clear.',
    initials: 'RY',
  },
  {
    name: 'Anita Devi',
    role: 'Entrepreneur, Bihar',
    text: 'MUDRA loan helped me start my tailoring unit. Now I employ 8 women from my village.',
    initials: 'AD',
  },
];

export const HOW_IT_WORKS = [
  { step: '01', title: 'Answer a few questions', desc: 'Tell us about yourself — age, occupation, income and state. Takes under 2 minutes.' },
  { step: '02', title: 'Get personalized matches', desc: 'Our engine ranks schemes you are eligible for based on your profile.' },
  { step: '03', title: 'Apply with confidence', desc: 'Follow step-by-step application instructions on the official portal.' },
];

// Local storage helpers for mock user state
export const getSavedSchemes = () => {
  try {
    return JSON.parse(localStorage.getItem('savedSchemes') || '[]');
  } catch {
    return [];
  }
};

export const toggleSavedScheme = (id) => {
  const list = getSavedSchemes();
  const next = list.includes(id) ? list.filter((x) => x !== id) : [...list, id];
  localStorage.setItem('savedSchemes', JSON.stringify(next));
  return next;
};

export const getProfile = () => {
  try {
    return JSON.parse(localStorage.getItem('userProfile') || 'null');
  } catch {
    return null;
  }
};

export const setProfile = (profile) => {
  localStorage.setItem('userProfile', JSON.stringify(profile));
};